apiVersion: v1
kind: Service
metadata:
  name: webagentff-svc
  labels:
    apps: webagentff
spec:
  type: NodePort
  ports:
  - port: 5900
    targetPort: ffagentport
    protocol: TCP
    targetPort: 5900
    nodePort: 30900
  selector:
    app: webagentff
