apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webagentff
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webagentff
    spec:
      containers:
      - name: webagentff
        image: registry.ng.bluemix.net/mycontainter/webautofirefox
        imagePullPolicy: Always
        env:
        - name: testbrowser
          value: Firefox
        ports:
        - containerPort: 5900
          name: ffagentport
        volumeMounts:
        - name: inputfolder
          mountPath: /usr/src/public/input
        - name: outputfolder
          mountPath: /usr/src/public/output
      volumes:
      - name: inputfolder
        persistentVolumeClaim:
          claimName: chance-input-pv-claim
      - name: outputfolder
        persistentVolumeClaim:
          claimName: chance-output-pv-claim
