

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_USER"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_USER"  (
		  "USERID" VARCHAR(200) NOT NULL ,
		  "PASSWORD" VARCHAR(20) NOT NULL ,
		  "USERNAME" VARCHAR(200) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_USER"

ALTER TABLE "DB2INST1"."T_USER"
	ADD CONSTRAINT "CC1502089262346" PRIMARY KEY
		("USERID");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONENV"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_EXECUTIONENV"  (
		  "PLANID" INTEGER NOT NULL ,
		  "OS" VARCHAR(20) NOT NULL ,
		  "BROWSER" VARCHAR(20) NOT NULL ,
		  "AGENTNAME" VARCHAR(100) )
		 IN "USERSPACE1"
		 ORGANIZE BY (
		  ( "PLANID" ) )
		 ;





------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONPLANDETAIL"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_EXECUTIONPLANDETAIL"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "PLANID" INTEGER NOT NULL ,
		  "EXECUTENO" INTEGER NOT NULL ,
		  "CASEID" INTEGER NOT NULL ,
		  "EXECUTEFLG" INTEGER )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONPLANDETAIL"

ALTER TABLE "DB2INST1"."T_EXECUTIONPLANDETAIL"
	ADD CONSTRAINT "CC1488952015021" PRIMARY KEY
		("ID");


ALTER TABLE "DB2INST1"."T_EXECUTIONPLANDETAIL" ALTER COLUMN "ID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_PARAM"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_PARAM"  (
		  "PARAMNAME" VARCHAR(250) NOT NULL ,
		  "PARAMVALUE" VARCHAR(250) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_PARAM"

ALTER TABLE "DB2INST1"."T_PARAM"
	ADD CONSTRAINT "CC1488953884380" PRIMARY KEY
		("PARAMNAME");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_APPLICATION"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_APPLICATION"  (
		  "APPID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +0
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "APPNAME" VARCHAR(100) NOT NULL ,
		  "APPDETAIL" VARCHAR(250) NOT NULL ,
		  "DBDRIVER" VARCHAR(250) NOT NULL ,
		  "DBURL" VARCHAR(250) NOT NULL ,
		  "DBUSER" VARCHAR(10) NOT NULL ,
		  "DBPASSWORD" VARCHAR(10) NOT NULL ,
		  "DBSCHEMA" VARCHAR(10) ,
		  "JIRAURL" CHAR(250) NOT NULL ,
		  "JIRAUSER" CHAR(100) NOT NULL ,
		  "JIRAPASSWORD" CHAR(100) NOT NULL ,
		  "JIRAPROJECTKEY" CHAR(20) NOT NULL ,
		  "HEADERHIGHT" INTEGER )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_APPLICATION"

ALTER TABLE "DB2INST1"."T_APPLICATION"
	ADD CONSTRAINT "CC1488947999489" PRIMARY KEY
		("APPID");


ALTER TABLE "DB2INST1"."T_APPLICATION" ALTER COLUMN "APPID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_CASEPARAMVALUE"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_CASEPARAMVALUE"  (
		  "CASEID" INTEGER NOT NULL ,
		  "CASEDETAILID" INTEGER NOT NULL ,
		  "SCENARIOUK" INTEGER NOT NULL ,
		  "ACTIONUK" BIGINT NOT NULL ,
		  "PARAMTYPE" INTEGER NOT NULL ,
		  "PARAMVALUE" VARCHAR(250) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_CASEPARAMVALUE"

ALTER TABLE "DB2INST1"."T_CASEPARAMVALUE"
	ADD CONSTRAINT "CC1488949457785" PRIMARY KEY
		("CASEID",
		 "CASEDETAILID",
		 "SCENARIOUK",
		 "ACTIONUK",
		 "PARAMTYPE",
		 "PARAMVALUE");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_CONFIG"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_CONFIG"  (
		  "ID" INTEGER NOT NULL ,
		  "CONFIGTYPE" VARCHAR(14) NOT NULL ,
		  "CONFIGORDER" INTEGER NOT NULL ,
		  "CONFIGNAME" VARCHAR(50) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_CONFIG"

ALTER TABLE "DB2INST1"."T_CONFIG"
	ADD CONSTRAINT "CC1491461436870" PRIMARY KEY
		("ID");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTEFLAG"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_EXECUTEFLAG"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "USERNAME" VARCHAR(50) NOT NULL ,
		  "FLAG" INTEGER NOT NULL ,
		  "ACTIVE" INTEGER NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTEFLAG"

ALTER TABLE "DB2INST1"."T_EXECUTEFLAG"
	ADD CONSTRAINT "CC1491371425545" PRIMARY KEY
		("ID");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_TEST_RESULT"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_TEST_RESULT"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "EXECUTETIMESTAMP" CHAR(14) NOT NULL ,
		  "COMPLETETIMESTAMP" CHAR(14) NOT NULL ,
		  "PLANID" INTEGER NOT NULL ,
		  "OS" VARCHAR(20) NOT NULL ,
		  "BROWSER" VARCHAR(20) NOT NULL ,
		  "USERID" VARCHAR(50) NOT NULL ,
		  "APPNAME" VARCHAR(50) NOT NULL ,
		  "PLANMEMO" VARCHAR(250) NOT NULL ,
		  "EXECUTENO" INTEGER NOT NULL ,
		  "CASEID" INTEGER NOT NULL ,
		  "CASENAME" VARCHAR(100) NOT NULL ,
		  "SCENARIONO" INTEGER NOT NULL ,
		  "SCENARIONAME" VARCHAR(100) NOT NULL ,
		  "PAGEORDER" INTEGER NOT NULL ,
		  "PAGENAME" VARCHAR(100) NOT NULL ,
		  "ACTIONNO" INTEGER NOT NULL ,
		  "ACTITONNAME" VARCHAR(100) NOT NULL ,
		  "ACTITONDETAIL" VARCHAR(250) NOT NULL ,
		  "OBJECTNAME" VARCHAR(100) NOT NULL ,
		  "PARAM" VARCHAR(1000) NOT NULL ,
		  "STATUS" VARCHAR(10) NOT NULL ,
		  "DETAIL" VARCHAR(1000) NOT NULL ,
		  "FILENAME" VARCHAR(250) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_TEST_RESULT"

ALTER TABLE "DB2INST1"."T_TEST_RESULT"
	ADD CONSTRAINT "CC1489541343485" PRIMARY KEY
		("ID");


ALTER TABLE "DB2INST1"."T_TEST_RESULT" ALTER COLUMN "ID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_PAGE"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_PAGE"  (
		  "PAGEID" VARCHAR(100) NOT NULL ,
		  "APPID" INTEGER NOT NULL ,
		  "PAGENAME" VARCHAR(100) NOT NULL ,
		  "PAGEDETAIL" VARCHAR(250) NOT NULL ,
		  "HEADERHIGHT" INTEGER NOT NULL WITH DEFAULT 99999 )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_PAGE"

ALTER TABLE "DB2INST1"."T_PAGE"
	ADD CONSTRAINT "CC1488953416389" PRIMARY KEY
		("PAGEID",
		 "APPID");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONPLANGROUP"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_EXECUTIONPLANGROUP"  (
		  "GROUPID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "GROUPNAME" VARCHAR(500) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONPLANGROUP"

ALTER TABLE "DB2INST1"."T_EXECUTIONPLANGROUP"
	ADD CONSTRAINT "CC1511253249724" PRIMARY KEY
		("GROUPID");


ALTER TABLE "DB2INST1"."T_EXECUTIONPLANGROUP" ALTER COLUMN "GROUPID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONPLANMAIN"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_EXECUTIONPLANMAIN"  (
		  "PLANID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +13
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "APPID" INTEGER ,
		  "PLANMEMO" VARCHAR(250) ,
		  "NEXTPLANDATE" CHAR(8) ,
		  "NEXTPLANTIME" CHAR(9) ,
		  "LASTEXECUTEDATE" CHAR(8) ,
		  "LASTEXECUTETIME" CHAR(9) ,
		  "NOTIFYEMAILADDRESS" CHAR(200) ,
		  "EXECUTEFLAG" INTEGER ,
		  "HIGHLIGHTOBJECT" INTEGER ,
		  "GROUPID" INTEGER ,
		  "ERRORSTOPFLAG" INTEGER ,
		  "DISPLAYORDER" INTEGER )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_EXECUTIONPLANMAIN"

ALTER TABLE "DB2INST1"."T_EXECUTIONPLANMAIN"
	ADD CONSTRAINT "CC1488952706081" PRIMARY KEY
		("PLANID");


ALTER TABLE "DB2INST1"."T_EXECUTIONPLANMAIN" ALTER COLUMN "PLANID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_APICASEMAIN"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_APICASEMAIN"  (
		  "CASEID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +99999999999
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "APPID" INTEGER ,
		  "CASEDETAIL" VARCHAR(250) )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_APICASEMAIN"

ALTER TABLE "DB2INST1"."T_APICASEMAIN"
	ADD CONSTRAINT "KEY_APICASEMAIN" PRIMARY KEY
		("CASEID");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_REQUESTTEMPLATE"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_REQUESTTEMPLATE"  (
		  "REQTEMPID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +99999999999
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "DESCRIPTION" VARCHAR(250) NOT NULL ,
		  "METHOD" VARCHAR(10) NOT NULL ,
		  "REQURL" VARCHAR(250) NOT NULL ,
		  "REQBODY" VARCHAR(250) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_REQUESTTEMPLATE"

ALTER TABLE "DB2INST1"."T_REQUESTTEMPLATE"
	ADD CONSTRAINT "KEY_REQTEMP" PRIMARY KEY
		("REQTEMPID");


ALTER TABLE "DB2INST1"."T_REQUESTTEMPLATE" ALTER COLUMN "REQTEMPID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_REQUESTTEMPLATEPARAM"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_REQUESTTEMPLATEPARAM"  (
		  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +99999999999
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "REQTEMPID" BIGINT NOT NULL ,
		  "PARAMNO" INTEGER NOT NULL ,
		  "PARAMNAME" VARCHAR(100) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_REQUESTTEMPLATEPARAM"

ALTER TABLE "DB2INST1"."T_REQUESTTEMPLATEPARAM"
	ADD CONSTRAINT "KEY_REQTEMPPARAM" PRIMARY KEY
		("ID");


ALTER TABLE "DB2INST1"."T_REQUESTTEMPLATEPARAM" ALTER COLUMN "ID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_APICASEDETAIL"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_APICASEDETAIL"  (
		  "CASEDETAILID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +99999999999
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "CASEID" BIGINT NOT NULL ,
		  "NO" BIGINT NOT NULL ,
		  "ACTIONTYPE" VARCHAR(100) NOT NULL ,
		  "REQTEMPID" BIGINT ,
		  "DESCRIPTION" VARCHAR(500) NOT NULL ,
		  "EXPECTVALUE" VARCHAR(250) ,
		  "XPATH" VARCHAR(250) ,
		  "PROPNAME" VARCHAR(100) ,
		  "RUNTIMEPARAMNAME" VARCHAR(100) )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_APICASEDETAIL"

ALTER TABLE "DB2INST1"."T_APICASEDETAIL"
	ADD CONSTRAINT "KEY_REQTEMPPARAM" PRIMARY KEY
		("CASEDETAILID");


ALTER TABLE "DB2INST1"."T_APICASEDETAIL" ALTER COLUMN "CASEDETAILID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_TEST_APIRESULT"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_TEST_APIRESULT"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "EXECUTETIMESTAMP" CHAR(14) NOT NULL ,
		  "COMPLETETIMESTAMP" CHAR(14) NOT NULL ,
		  "PLANID" INTEGER NOT NULL ,
		  "APPNAME" VARCHAR(50) NOT NULL ,
		  "CASEID" BIGINT NOT NULL ,
		  "CASEDESCRIPTION" VARCHAR(500) NOT NULL ,
		  "ACTIONNO" BIGINT NOT NULL ,
		  "ACTIONTYPE" VARCHAR(100) NOT NULL ,
		  "REQUESTMETHOD" VARCHAR(10) ,
		  "REQUESTURL" VARCHAR(250) ,
		  "REQUESTBODY" VARCHAR(250) ,
		  "DESCRIPTION" VARCHAR(500) NOT NULL ,
		  "EXPECTVALUE" VARCHAR(250) ,
		  "ACTURALVALUE" VARCHAR(250) ,
		  "XPATH" VARCHAR(250) ,
		  "PROPNAME" VARCHAR(100) ,
		  "RUNTIMEPARAMNAME" VARCHAR(100) ,
		  "STATUS" VARCHAR(100) ,
		  "DETAIL" VARCHAR(250) )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_TEST_APIRESULT"

ALTER TABLE "DB2INST1"."T_TEST_APIRESULT"
	ADD CONSTRAINT "KEY_APIRESULT" PRIMARY KEY
		("ID");


------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_OBJECT"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_OBJECT"  (
		  "OBJECTID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "APPID" INTEGER NOT NULL ,
		  "PAGEID" VARCHAR(100) NOT NULL ,
		  "OBJECTNAME" VARCHAR(100) NOT NULL ,
		  "OBJECTTYPE" VARCHAR(100) NOT NULL ,
		  "INFRAME" INTEGER NOT NULL ,
		  "IDENTIFIER" CHAR(10) NOT NULL ,
		  "IDENTIFYKEY" VARCHAR(1000) NOT NULL ,
		  "PARAMNAME" VARCHAR(1000) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_OBJECT"

ALTER TABLE "DB2INST1"."T_OBJECT"
	ADD CONSTRAINT "CC1488953001307" PRIMARY KEY
		("OBJECTID");


ALTER TABLE "DB2INST1"."T_OBJECT" ALTER COLUMN "OBJECTID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_PAGEACTIONMAIN"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_PAGEACTIONMAIN"  (
		  "PAGEACTIONID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "APPID" INTEGER NOT NULL ,
		  "PAGEID" VARCHAR(200) NOT NULL ,
		  "PAGEACTIONDETAIL" VARCHAR(100) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_PAGEACTIONMAIN"

ALTER TABLE "DB2INST1"."T_PAGEACTIONMAIN"
	ADD CONSTRAINT "CC1490079679215" PRIMARY KEY
		("PAGEACTIONID");


ALTER TABLE "DB2INST1"."T_PAGEACTIONMAIN" ALTER COLUMN "PAGEACTIONID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_PAGEACTION"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_PAGEACTION"  (
		  "ACTIONUK" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +9223372036854775807
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "PAGEACTIONID" INTEGER NOT NULL ,
		  "ACTIONNO" INTEGER NOT NULL ,
		  "ACTIONNAME" CHAR(100) NOT NULL ,
		  "ACTIONDETAIL" VARCHAR(200) NOT NULL ,
		  "OBJECTID" INTEGER NOT NULL ,
		  "PARAMNAME" VARCHAR(250) NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_PAGEACTION"

ALTER TABLE "DB2INST1"."T_PAGEACTION"
	ADD CONSTRAINT "CC1489034049209" PRIMARY KEY
		("ACTIONUK");


ALTER TABLE "DB2INST1"."T_PAGEACTION" ALTER COLUMN "ACTIONUK" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_SCENARIOMAIN"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_SCENARIOMAIN"  (
		  "SCENARIOID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "SCENARIONAME" VARCHAR(100) NOT NULL ,
		  "SCENARIODETAIL" VARCHAR(150) ,
		  "REVIEW" CHAR(1) NOT NULL ,
		  "APPID" INTEGER )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_SCENARIOMAIN"

ALTER TABLE "DB2INST1"."T_SCENARIOMAIN"
	ADD CONSTRAINT "CC1488953985450" PRIMARY KEY
		("SCENARIOID");


ALTER TABLE "DB2INST1"."T_SCENARIOMAIN" ALTER COLUMN "SCENARIOID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_SCENARIOPROCESS"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_SCENARIOPROCESS"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "SCENARIOID" INTEGER NOT NULL ,
		  "PAGEORDER" INTEGER NOT NULL ,
		  "PAGEACTIONID" INTEGER NOT NULL ,
		  "COMMENT" VARCHAR(100) )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_SCENARIOPROCESS"

ALTER TABLE "DB2INST1"."T_SCENARIOPROCESS"
	ADD CONSTRAINT "CC1488954080301" PRIMARY KEY
		("ID");


ALTER TABLE "DB2INST1"."T_SCENARIOPROCESS" ALTER COLUMN "ID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_CASEMAIN"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_CASEMAIN"  (
		  "CASEID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +9223372036854775807
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "CASENAME" VARCHAR(100) NOT NULL ,
		  "CASEDETAIL" VARCHAR(250) ,
		  "REVIEWKBN" CHAR(1) NOT NULL ,
		  "APPID" INTEGER NOT NULL )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_CASEMAIN"

ALTER TABLE "DB2INST1"."T_CASEMAIN"
	ADD CONSTRAINT "CC1489033189891" PRIMARY KEY
		("CASEID");


ALTER TABLE "DB2INST1"."T_CASEMAIN" ALTER COLUMN "CASEID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_CASEDETAIL"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_CASEDETAIL"  (
		  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +0
		    MAXVALUE +9223372036854775807
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "CASEID" INTEGER NOT NULL ,
		  "SCENARIONO" INTEGER NOT NULL ,
		  "SCENARIOID" INTEGER NOT NULL ,
		  "EXECUTEFLAG" VARCHAR(1) )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_CASEDETAIL"

ALTER TABLE "DB2INST1"."T_CASEDETAIL"
	ADD CONSTRAINT "CC1488948348268" PRIMARY KEY
		("ID");


ALTER TABLE "DB2INST1"."T_CASEDETAIL" ALTER COLUMN "ID" RESTART WITH 1;

------------------------------------------------
-- �\�� DDL �X�e�[�g�����g "DB2INST1"."T_APICASEPARAM"
------------------------------------------------


CREATE TABLE "DB2INST1"."T_APICASEPARAM"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
		    START WITH +1
		    INCREMENT BY +1
		    MINVALUE +1
		    MAXVALUE +2147483647
		    NO CYCLE
		    NO CACHE
		    NO ORDER ) ,
		  "CASEID" BIGINT NOT NULL ,
		  "ACTIONNO" BIGINT NOT NULL ,
		  "PARAMNO" BIGINT NOT NULL ,
		  "PARAMVALUE" VARCHAR(250) )
		 IN "USERSPACE1" ;


-- �\�̎��L�[�� DDL �X�e�[�g�����g "DB2INST1"."T_APICASEPARAM"

ALTER TABLE "DB2INST1"."T_APICASEPARAM"
	ADD CONSTRAINT "KEY_APICASEPARAM" PRIMARY KEY
		("ID");


ALTER TABLE "DB2INST1"."T_APICASEPARAM" ALTER COLUMN "ID" RESTART WITH 1;






----------------------------

-- �r���[�� DDL �X�e�[�g�����g

----------------------------
SET CURRENT SCHEMA = "DB2INST1";
SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","DB2INST1";
CREATE VIEW V_TEST_RESULT
AS
SELECT R2.*,ER.ERRSTEPS FROM
((SELECT R1.*,FR.FAILSTEPS FROM (
(SELECT BASE.*,ALLS.ALLSTEPS FROM
(SELECT EXECUTENO, TR.CASEID, TR.CASENAME, CM.CASEDETAIL,EXECUTETIMESTAMP, USERID, OS, BROWSER, APPNAME, PLANMEMO,COUNT(1) AS EXESTEPS
FROM T_TEST_RESULT TR,T_CASEMAIN CM WHERE TR.CASEID=CM.CASEID
GROUP BY EXECUTENO, TR.CASEID, TR.CASENAME,CM.CASEDETAIL, EXECUTETIMESTAMP, USERID, OS, BROWSER, APPNAME, PLANMEMO) BASE
JOIN (SELECT CM.CASEID,count(CM.CASEID) AS ALLSTEPS
FROM T_CASEMAIN CM , T_CASEDETAIL CD,T_SCENARIOPROCESS SP,T_PAGEACTION PA
WHERE CM.CASEID=CD.CASEID
AND CD.SCENARIOID=SP.SCENARIOID
AND SP.PAGEACTIONID=PA.PAGEACTIONID
GROUP BY CM.CASEID) ALLS ON BASE.CASEID=ALLS.CASEID) R1 LEFT JOIN
(SELECT EXECUTETIMESTAMP,CASEID, CASENAME, USERID, OS, BROWSER, APPNAME, PLANMEMO,EXECUTENO,COUNT(EXECUTENO) AS FAILSTEPS
FROM T_TEST_RESULT WHERE STATUS='Fail'
GROUP BY EXECUTETIMESTAMP,CASEID, CASENAME, USERID, OS, BROWSER, APPNAME, PLANMEMO,EXECUTENO) FR
ON R1.EXECUTETIMESTAMP=FR.EXECUTETIMESTAMP
AND R1.CASEID=FR.CASEID
AND R1.CASENAME=FR.CASENAME
AND R1.USERID=FR.USERID
AND R1.OS=FR.OS
AND R1.BROWSER=FR.BROWSER
AND R1.APPNAME=FR.APPNAME
AND R1.PLANMEMO=FR.PLANMEMO
AND R1.EXECUTENO=FR.EXECUTENO)) R2 LEFT JOIN
(SELECT EXECUTETIMESTAMP,CASEID, CASENAME, USERID, OS, BROWSER, APPNAME, PLANMEMO,EXECUTENO,COUNT(EXECUTENO) AS ERRSTEPS
FROM T_TEST_RESULT
WHERE STATUS='Error'
GROUP BY EXECUTETIMESTAMP,CASEID, CASENAME, USERID, OS, BROWSER, APPNAME, PLANMEMO,EXECUTENO) ER
ON R2.EXECUTETIMESTAMP=ER.EXECUTETIMESTAMP
AND R2.CASEID=ER.CASEID
AND R2.CASENAME=ER.CASENAME
AND R2.USERID=ER.USERID
AND R2.OS=ER.OS
AND R2.BROWSER=ER.BROWSER
AND R2.APPNAME=ER.APPNAME
AND R2.PLANMEMO=ER.PLANMEMO
AND R2.EXECUTENO=ER.EXECUTENO);
