#debug模式
#FROM selenium/standalone-firefox-debug:2.53.0
#普通模式
FROM blockchain-03.cn.ibm.com:83/library/base-firefox
ADD ./webautotest /usr/src/
VOLUME ["/usr/src/output","/usr/src/input","/usr/src/download"]
